logging:
  level:
    root: info
    com.example.receipt_processor: debug
  file:
    name: logs/application.log

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: receipt-processor
  server:
    port: 8080
  resources:
    static-locations: classpath:/static/, classpath:/public/, classpath:/resources/, classpath:/META-INF/resources/

management:
  endpoints:
    web:
      exposure:
        include: "*"
